export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_ERROR = 'LOG_IN_ERROR';

export const APPS_LOAD_SUCCESS = 'APPS_LOAD_SUCCESS';
export const APPS_LOAD_ERROR = 'APPS_LOAD_ERROR';
export const APPS_EDIT_SUCCESS = 'APPS_EDIT_SUCCESS';
export const APPS_EDIT_ERROR = 'APPS_EDIT_ERROR';

export const USERS_LOAD_SUCCESS = 'USERS_LOAD_SUCCESS';
export const USERS_LOAD_ERROR = 'USERS_LOAD_ERROR';
